({
  buildColors: true,
  buildTypography: true,
  buildObjects: true,
  injectFooters: true,
  perfLog: true,
  selectedThemes: ['Blue',],
  primaryStyleTheme: 'Blue',
  isReverseMode: false,
  colorMode: 'RGB',
  selectedFooterVariant: 'All Footers',
  customFooterDirectory: 'C:\\Work\\EPS',
  footerFormat: '.eps',
  selectedFont: 'Noto Sans',
  baseLeadingRatio: 1.25,
  scaleRatio: 1.25,
  updateMargins: true,
  injectSpecimen: false,
  exportINDD: true,
})
